#!/bin/bash
# Issue Catfight Processor
# Runs all open issues through model gauntlet, posts analysis as comments

REPO="dirtybirdnj/clood"
# ALL THE MODELS - failures teach us for free
MODELS="qwen2.5-coder:32b,codestral:22b,qwen2.5-coder:14b,deepseek-r1:8b,llama3.1:8b,llama3-groq-tool-use:8b,qwen2.5-coder:3b,tinyllama"
LOG_DIR="/tmp/catfight-triage-$(date +%Y%m%d-%H%M%S)"
mkdir -p "$LOG_DIR"

echo "🐱 ISSUE CATFIGHT PROCESSOR"
echo "==========================="
echo "Repo: $REPO"
echo "Models: $MODELS"
echo "Log dir: $LOG_DIR"
echo ""

# Get all open issues - save to file to avoid JSON parsing issues with bash
ISSUES_FILE="/tmp/catfight-issues-$$.json"
gh issue list --repo "$REPO" --state open --limit 100 --json number,title,body > "$ISSUES_FILE"

# Count issues
COUNT=$(python3 -c "import json; print(len(json.load(open('$ISSUES_FILE'))))")
echo "Processing $COUNT issues..."
echo ""

# Process each issue
python3 << PYEOF
import json
import sys
import subprocess
import os
import time
from datetime import datetime

# Read from file instead of stdin to avoid bash JSON issues
with open('$ISSUES_FILE', 'r') as f:
    issues = json.load(f)

def log(msg):
    ts = datetime.now().strftime('%H:%M:%S')
    print(f'[{ts}] {msg}', flush=True)

def check_ollama():
    """Health check - make sure ollama is responding"""
    try:
        result = subprocess.run(['curl', '-s', 'http://localhost:11434/api/tags'],
                              capture_output=True, timeout=10)
        return result.returncode == 0
    except:
        return False
log_dir = '$LOG_DIR'
models = '$MODELS'
repo = '$REPO'

prompt_template = '''You are analyzing GitHub Issue #{number} from the clood project (a CLI tool for orchestrating local LLM inference across a server garden).

## ISSUE
**Title:** {title}

**Body:**
{body}

---

## YOUR TASK
Analyze this issue and provide a structured response that will be posted as a GitHub comment.

Format your response EXACTLY like this:

## 🤖 Model Analysis: {model_name}

### Understanding
[2-3 sentence summary of what is being requested]

### Scope Estimate
**Size:** [XS/S/M/L/XL]
**Reasoning:** [Why this size]

### Implementation Plan
1. [Step 1]
2. [Step 2]
3. [etc]

### Code Sketch
\`\`\`[language]
[Key code or pseudocode if applicable, otherwise write \"N/A - planning/design issue\"]
\`\`\`

### Diagram
\`\`\`mermaid
[Mermaid diagram if helpful, otherwise write \"N/A\"]
\`\`\`

### Open Questions
- [Question 1]
- [Question 2]

---
*Generated by clood catfight triage - {model_name}*
'''

for i, issue in enumerate(issues):
    num = issue['number']
    title = issue['title']
    body = issue['body'] or 'No description provided.'

    log(f'[{i+1}/{len(issues)}] Processing Issue #{num}: {title[:50]}...')

    # De-icing: Check ollama is alive before each issue
    if not check_ollama():
        log('  ⚠ Ollama not responding, waiting 30s...')
        time.sleep(30)
        if not check_ollama():
            log('  ✗ Ollama still down, skipping issue')
            continue

    # Create prompt
    prompt = prompt_template.format(
        number=num,
        title=title,
        body=body,
        model_name='{MODEL}'  # Placeholder, each model fills this
    )

    # Save prompt
    prompt_file = f'{log_dir}/issue-{num}-prompt.txt'
    with open(prompt_file, 'w') as f:
        f.write(prompt)

    # Run catfight
    result_file = f'{log_dir}/issue-{num}-results.txt'
    cmd = f'~/bin/clood catfight -m \"{models}\" -f \"{prompt_file}\" > \"{result_file}\" 2>&1'

    try:
        subprocess.run(cmd, shell=True, timeout=900)  # 15 min timeout (32b is slow)
        log('  ✓ Catfight complete')

        # Read results and extract winner response
        with open(result_file, 'r') as f:
            results = f.read()

        # Save full results
        log(f'  ✓ Results saved to {result_file}')

        # Post comment to GitHub (just the results summary for now)
        # We'll extract the best response in a more sophisticated way later
        comment = f'''## 🐱 Catfight Triage Results

This issue was analyzed by the clood model gauntlet.

**Models:** {models}

<details>
<summary>Click to expand full analysis</summary>

\`\`\`
{results[-8000:] if len(results) > 8000 else results}
\`\`\`

</details>

---
*Automated triage by clood catfight - review in planning ritual*
'''

        # Post to GitHub
        comment_file = f'{log_dir}/issue-{num}-comment.md'
        with open(comment_file, 'w') as f:
            f.write(comment)

        post_cmd = f'gh issue comment {num} --repo {repo} --body-file \"{comment_file}\"'
        subprocess.run(post_cmd, shell=True)
        log(f'  ✓ Comment posted to Issue #{num}')

        # De-icing: Sleep between issues to avoid GitHub rate limiting
        log('  💤 Sleeping 5s before next issue...')
        time.sleep(5)

    except subprocess.TimeoutExpired:
        log(f'  ✗ Timeout on Issue #{num} (15 min exceeded)')
    except Exception as e:
        log(f'  ✗ Error on Issue #{num}: {e}')

print('=========================')
print('🏁 CATFIGHT TRIAGE COMPLETE')
print(f'Results saved to: {log_dir}')
PYEOF
